services:
    client:
        container_name: dominators-client
        image: dominators-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
                CLIENT_PORT: ${CLIENT_PORT}
                SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${CLIENT_PORT}:${CLIENT_PORT}"
        environment:
            - INTERNAL_SERVER_URL=${INTERNAL_SERVER_URL}
            - EXTERNAL_SERVER_URL=${EXTERNAL_SERVER_URL}
            - CLIENT_PORT=${CLIENT_PORT}
            - SERVER_PORT=${SERVER_PORT}

    server:
        container_name: dominators-server
        image: dominators-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
                SERVER_PORT: ${SERVER_PORT}
        depends_on:
            - postgres
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
            SERVER_PORT: ${SERVER_PORT}

    postgres:
        image: postgres:14
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /tmp
        volumes:
            - ./tmp/pgdata:/var/lib/postgresql/data
        restart: always
