name: Assign Reviewers on Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: kentaro-m/auto-assign-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            samura-io
            CatchOnGenjutsu
            doroshenko29
            lira-bazh
            JulKoroleva
